# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

# Railway requires cache IDs to begin with "build-"
RUN --mount=type=cache,id=build-npm-cache \
    npm ci --ignore-scripts --omit=dev

COPY . .

RUN --mount=type=cache,id=build-npm-cache \
    npm run build

RUN --mount=type=cache,id=build-npm-cache \
    npm link

# Runtime image
FROM node:20-slim

COPY scripts/notion-openapi.json /usr/local/scripts/
COPY --from=builder /usr/local/lib/node_modules/@notionhq/notion-mcp-server /usr/local/lib/node_modules/@notionhq/notion-mcp-server
COPY --from=builder /usr/local/bin/notion-mcp-server /usr/local/bin/notion-mcp-server

ENV OPENAPI_MCP_HEADERS="{}"

ENTRYPOINT ["notion-mcp-server"]
