# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

# Railway requires BOTH:
# 1. id must start with "build-"
# 2. target must be under /root/.cache/
RUN --mount=type=cache,id=build-npm-cache,target=/root/.cache/npm \
    npm ci --ignore-scripts --omit=dev

COPY . .

RUN --mount=type=cache,id=build-npm-cache,target=/root/.cache/npm \
    npm run build

RUN --mount=type=cache,id=build-npm-cache,target=/root/.cache/npm \
    npm link

# Runtime stage
FROM node:20-slim

COPY scripts/notion-openapi.json /usr/local/scripts/
COPY --from=builder /usr/local/lib/node_modules/@notionhq/notion-mcp-server /usr/local/lib/node_modules/@notionhq/notion-mcp-server
COPY --from=builder /usr/local/bin/notion-mcp-server /usr/local/bin/notion-mcp-server

ENV OPENAPI_MCP_HEADERS="{}"

ENTRYPOINT ["notion-mcp-server"]
